# ------------------------------------------------
# Deploy to Development Environment
# ------------------------------------------------
deploy-dev:
  name: Deploy to Dev
  runs-on: ubuntu-latest
  environment: dev # Links to the 'dev' GitHub environment for secrets and protection rules
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure Azure Credentials
      uses: azure/login@v1
      with:
        client-id: ${{ ae804023-6493-4238-ba56-8ec6171327f0 }}
        tenant-id: ${{ 004cf285-b50e-4fde-8f95-bd7de25ebe69 }}
        subscription-id: ${{ 29760404-2fa8-46e6-b53d-2e616c1be5ce }} # Use dev-specific subscription ID

    - name: Terraform Init and Apply (Dev)
      run: |
      # Navigate to the dev environment directory
      cd environments/dev
      terraform init -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT_DEV }}" -backend-config="container_name=tfstate" -backend-config="key=dev.terraform.tfstate"
      terraform apply -auto-approve
