environment = "test"
location    = "West US 2" # Different region for Test
project_name = "MyWebApp"
resource_group_suffix = "test"
static_web_app_sku_tier = "Free"
static_web_app_sku_size = "Free"
storage_account_replication_type = "ZRS" # [30] (Zone redundancy for Test)
budget_amount = 150.0 # USD
budget_contact_email = ["devops-alerts@example.com"]